---
- name: Instalar Apache
  apt: 
    name: 
      - apache2
      - libapache2-mod-php
    state: present

- name: Modificar ServerName en fichero Apache2
  lineinfile:
       path: "{{ apache_conf }}"
       state: present
       regexp: '.*ServerName.*'
       line: '    ServerName {{ webserver_hostname }}'
  notify: reiniciar apache

- name: Modificar ServerAdmin en fichero Apache2
  lineinfile:
       path: "{{ apache_conf }}"
       state: present
       regexp: '.*ServerAdmin.*'
       line: '    ServerAdmin {{ mail_webmaster }}'
  notify: reiniciar apache

- name: Crear pagina web
  template:
        src: index.html.j2
        dest: "{{ destino_web }}/index.html"
        owner: www-data
        group: www-data
        mode: 0644

- name: Descargar web
  get_url:
    url: "{{ web_url }}"
    dest: "/tmp/"
  delegate_to: master

- name: Descomprimir fichero en target
  unarchive:
    src: /tmp/miapp.tar.bz
    dest: "{{ destino_web }}"

- name: Borrar fichero
  file:
    state: absent
    path: /tmp/miapp.tar.bz
  delegate_to: master

- name: Esperar a que el fichero de contraseña esté creado
  wait_for:
    path: "roles/mysql/passwords/{{ mysql_user }}/mysqlpassword"
  delegate_to: master

- name: Configurar la bbdd en la aplicacion
  lineinfile:
    dest: "{{ destino_web }}/config.php"
    regexp: "{{ item.regexp }}"
    line: "{{ item.reemplazo }}"
    state: present
  loop:
    - { regexp: '^\$servername*=*', reemplazo: '$servername = "10.0.2.5";' }
    - { regexp: '^\$username*=*', reemplazo: '$username = "{{ mysql_user }}";' }
    - { regexp: '^\$password*=*', reemplazo: '$password = {{ mysql_pass }};' }
    - { regexp: '^\$dbname*=*', reemplazo: '$dbname = "miapp";' }

- name: Eliminar el index.html
  file:
    path: "{{ web_url }}/index.html"
    state: absent
  notify: reiniciar apache
