---
- name: Practica de tareas sincronas
  hosts: target1
  vars:
    tiempo_espera: 10

  tasks: 
  - name: La hora es
    command: date
    register: hora
  - debug: var=hora.stdout

  - name: Esperando
    shell: "sleep {{ tiempo_espera }}"
  
  - name: La hora es
    command: date
    register: hora
  - debug: var=hora.stdout
